// Code generated by Slice Machine. DO NOT EDIT.

import Hero from './Hero';
import HomeAboutUs from './HomeAboutUs';
import Image from './Image';
import ImageCards from './ImageCards';
import MainCarousel from './MainCarousel';
import Quote from './Quote';
import RowButton from './RowButton';
import Text from './Text';
import TextWithHeader from './TextWithHeader';
import TextWithImage from './TextWithImage';

export {
	Hero,
	HomeAboutUs,
	Image,
	ImageCards,
	MainCarousel,
	Quote,
	RowButton,
	Text,
	TextWithHeader,
	TextWithImage,
};

export const components = {
	hero: Hero,
	home_about_us: HomeAboutUs,
	image: Image,
	image_cards: ImageCards,
	main_carousel: MainCarousel,
	quote: Quote,
	row_button: RowButton,
	text: Text,
	text_with_header: TextWithHeader,
	text_with_image: TextWithImage,
};
