// Code generated by Slice Machine. DO NOT EDIT.

import GoogleMaps from './GoogleMaps';
import Hero from './Hero';
import HomeAboutUs from './HomeAboutUs';
import Image from './Image';
import ImageCards from './ImageCards';
import Quote from './Quote';
import Text from './Text';
import TextWithHeader from './TextWithHeader';
import TextWithImage from './TextWithImage';

export {
	GoogleMaps,
	Hero,
	HomeAboutUs,
	Image,
	ImageCards,
	Quote,
	Text,
	TextWithHeader,
	TextWithImage,
};

export const components = {
	google_maps: GoogleMaps,
	hero: Hero,
	home_about_us: HomeAboutUs,
	image: Image,
	image_cards: ImageCards,
	quote: Quote,
	text: Text,
	text_with_header: TextWithHeader,
	text_with_image: TextWithImage,
};
