// Code generated by Slice Machine. DO NOT EDIT.

import ArticleCards from './ArticleCards';
import Hero from './Hero';
import HomeAboutUs from './HomeAboutUs';
import Image from './Image';
import ImageCards from './ImageCards';
import MainCarousel from './MainCarousel';
import ProductItems from './ProductItems';
import Quote from './Quote';
import RowButton from './RowButton';
import Text from './Text';
import TextWithHeader from './TextWithHeader';
import TextWithImage from './TextWithImage';
import TilingWordImage from './TilingWordImage';

export {
	ArticleCards,
	Hero,
	HomeAboutUs,
	Image,
	ImageCards,
	MainCarousel,
	ProductItems,
	Quote,
	RowButton,
	Text,
	TextWithHeader,
	TextWithImage,
	TilingWordImage,
};

export const components = {
	article_cards: ArticleCards,
	hero: Hero,
	home_about_us: HomeAboutUs,
	image: Image,
	image_cards: ImageCards,
	main_carousel: MainCarousel,
	product_items: ProductItems,
	quote: Quote,
	row_button: RowButton,
	text: Text,
	text_with_header: TextWithHeader,
	text_with_image: TextWithImage,
	tiling_word_image: TilingWordImage,
};
